### ISSUE TITLE
organize project files.

### ISSUE THREAD

**Issue by distalx** [distalx/shoebox#1]
This is a [starter issue](http://hood.ie/blog/starter-issues.html), highly inspired by the great job of the folks at [Hoodie](http://hood.ie). 👍
## 🎃🙀👕🔭😻 Hacktoberfest: Trick or Treat!

If you haven’t yet, sign up for [Hacktoberfest](https://hacktoberfest.digitalocean.com/) to earn an exclusive T-Shirt.
## 🤔 What you will need to know

[github markdown](https://guides.github.com/features/mastering-markdown/)
## 🎯 The Goal

This is repository contains programming resources like free online courses,  study matirials, etc..
Move all the resource file into a `resource directory`. and linked them to `README.md`
## 📋 Step by Step

Working on your first Pull Request? You can learn how from this free series [How to Contribute to an Open Source Project on GitHub.](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github).
- [x] 🙋 Claim this issue: Comment below. Please 🙏 only claim if you want to start working on it within a day. Once claimed I'll add you as contributor to this repository.
- [x]  👌 Accept our invitation to this repository. Once accepted, assign yourself to this repository.
- [x] 🔄 replace the up for grabs label with in progress.
- [x] Setup the repository locally.
- [x] move all the files but leave `README.md` to  `stuff` directory.
- [x] link those files with their respective topic in `README.md` files.

```
[angular.js](stuff/angular-js.md)
```
- [x] Open a PR to master branch, mentioning this issue.

I'll merge it! 🎉

**Comment by minibhati93** [comment]
I would like to try this

**Comment by distalx** [comment]
@minibhati93  Sure! I've invited you to this repository, you can accept the invitation here: https://github.com/distalx/shoebox/invitations

**Comment by kaustubhhiware** [comment]
Can I drop a pull request for this ?
Asking since someone has been alloted , but I think I could do it quicker

**Comment by distalx** [comment]
Thanks @kaustubhhiware, But @minibhati93  had already left a comment to claim it would be disrespectful to @minibhati93 . This isn't a race!.

**Comment by distalx** [comment]
resolved in #2 .
