### ISSUE TITLE
Generate static pages using gatsbyjs  

### ISSUE THREAD

**Issue by distalx** [distalx/shoebox#3]
use [Gatsby](https://github.com/gatsbyjs/gatsby) and generate a static site.

for more details checkout this example, https://github.com/gatsbyjs/gatsby-starter-documentation

**Comment by rishabluthra** [comment]
Hey there!

I will get started on it but just a question, what do you want the static site to be composed of? Just the Readme?

**Comment by distalx** [comment]
Hey, Thanks a lot!

Thinking about list of topics should be the part of the left sidebar, on click the related resources can be displayed as a content. not sure how to go about it. any thoughts ?
i.e. http://gatsbyjs.github.io/gatsby-starter-documentation/docs/

I've invited you to this repository, you can accept the invitation here: https://github.com/distalx/shoebox/invitations

**Comment by rishabluthra** [comment]
Hey, I accepted the invitation, I will get started working on a simple site first, keep you posted!

**Comment by rishabluthra** [comment]
I submitted the pull request

**Comment by distalx** [comment]
Thanks for your contribution! I'll triage and take a look at it as soon as possible!
