### ISSUE TITLE
Setup github pages for project.

### ISSUE THREAD

**Issue by distalx** [distalx/shoebox#6]
setup github [pages](https://pages.github.com/) for static site.

**Comment by rishabluthra** [comment]
I can start working on it.

**Comment by rishabluthra** [comment]
@distalx 

I added the gh-pages branch with the site compiled, can you try and start github pages and see if it works?

**Comment by distalx** [comment]
I think `github-pages` is automatically locating the static site you have created and rendering it at http://distalx.github.io/shoebox/  So, now we just have to maintain shoebox-site. I'm not entirely sure that how dose it works actually. I'll read up on it. Any thoughts ?

**Comment by rishabluthra** [comment]
@distalx 

Ok basically, edit the files on the master branch and then do this command `gatsby build --prefix-links`, that will create a public folder and then copy the contents of the public folder and switch to the gh-pages branch and paste the contents there and push.

**Comment by winniehell** [comment]
@distalx It looks like this is solved. Could you close it or remove the hacktoberfest label?
